name = "substarter-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# You will set the actual secrets in the Cloudflare Dashboard later.
# DISCORD_PUBLIC_KEY = ""
# DISCORD_BOT_TOKEN = ""
# TELEGRAM_BOT_TOKEN = ""
# SUPABASE_URL = ""
# SUPABASE_SERVICE_ROLE_KEY = ""