name = "substarter-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://zjinaalsyovfwnaxbozy.supabase.co" 
DISCORD_PUBLIC_KEY = "bb9b59e29a355d2591a734ffb31276f5361b25deb957525571ba7cf081dcbbf8"